server.port: 8000

spring:
  application:
    name: webwallet

security:
  oauth2:
    resource:
      id: ${spring.application.name}


token:
  access-token:
    valid-seconds: 3600
  refresh-token:
    valid-seconds: 3600

walletd:
  host: localhost
  port: 14999
  url: http://${walletd.host}:${walletd.port}/json_rpc
  satellite:
    image: iridiumdev/webwallet-satellite:latest
    command: ["--testnet", "--local", "--data-dir=/data", "--container-file=/data/wallet"]

  dispatcher:
    name: dispatcher
    image: jwilder/nginx-proxy:latest
    ports:
      - "${walletd.port}:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
  network:
    name: walletd-sats


docker:
  socket: unix:///var/run/docker.sock
  pull-images:
    - ${walletd.satellite.image}
    - ${walletd.dispatcher.image}
