server.port: 8000

spring:
  application:
    name: webwallet
  resources:
    static-locations: file:webapp/dist/webapp/,classpath:/static/

security:
  oauth2:
    resource:
      id: ${spring.application.name}

jwt:
  # CHANGE THE secret FOR PRODUCTION!
  secret: f54eb595a95c2b7cb7cce3a5c7ef071bda82474be6d27b00c2f8c88d0b47481c30f502fe5fb1a1498a03686cc7651a9f09cca350f82c27c57d5dbf5e109341dc
  algorithm: HS512
  issuer: ird.cash
  access-token:
    valid-seconds: 300
    type: ACCESS
  refresh-token:
    valid-seconds: 3600
    type: REFRESH



walletd:
  host: localhost
  port: 14999
  url: http://${walletd.host}:${walletd.port}/json_rpc
  satellite:
    image: iridiumdev/webwallet-satellite:latest
    command: ["--testnet", "--local", "--data-dir=/data", "--container-file=/data/wallet"]

  dispatcher:
    name: dispatcher
    image: jwilder/nginx-proxy:latest
    ports:
      - "${walletd.port}:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
  network:
    name: walletd-sats


docker:
  socket: unix:///var/run/docker.sock
  pull-images:
    - ${walletd.satellite.image}
    - ${walletd.dispatcher.image}


logging:
  level:
    cash.ird: DEBUG